#ifndef INDIVIDUALPROJECT_CONSTANTS_H
#define INDIVIDUALPROJECT_CONSTANTS_H

//Screen dimension constants
const int SCREEN_WIDTH = 1920;
const int SCREEN_HEIGHT = 1080;

const int BLOCK_WIDTH = 16;


#endif //INDIVIDUALPROJECT_CONSTANTS_H
