#ifndef INDIVIDUALPROJECT_CONSTANTS_H
#define INDIVIDUALPROJECT_CONSTANTS_H

//Screen dimension constants
const int SCREEN_WIDTH = 1080;
const int SCREEN_HEIGHT = 720;


#endif //INDIVIDUALPROJECT_CONSTANTS_H
