#ifndef INDIVIDUALPROJECT_CONSTANTS_H
#define INDIVIDUALPROJECT_CONSTANTS_H

//Screen dimension constants
const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;


#endif //INDIVIDUALPROJECT_CONSTANTS_H
